(() => {
"use strict";
const API="https://api.airplanes.live/v2", MAN={lat:53.3537,lon:-2.27495};
const carriers={BAW:"British Airways",EZY:"easyJet",RYR:"Ryanair",RUK:"Ryanair UK",EXS:"Jet2",TOM:"TUI Airways",VIR:"Virgin Atlantic",UAE:"Emirates",QTR:"Qatar Airways",KLM:"KLM",DLH:"Lufthansa",AFR:"Air France",EIN:"Aer Lingus",WZZ:"Wizz Air",LOG:"Loganair",SAS:"SAS",AAL:"American Airlines",UAL:"United Airlines",DAL:"Delta Air Lines",SIA:"Singapore Airlines",THY:"Turkish Airlines",IBE:"Iberia",TAP:"TAP Air Portugal",SWR:"Swiss",BEL:"Brussels Airlines",NPT:"West Atlantic UK",CLF:"Centreline",REV:"RVL Aviation",GMA:"Gama Aviation"};
const $=id=>document.getElementById(id), ui={screen:$("screen"),live:$("liveText"),updated:$("updated"),refresh:$("refreshBtn"),settingsBtn:$("settingsBtn"),dialog:$("settings"),radius:$("radius"),interval:$("interval"),radiusValue:$("radiusValue"),intervalValue:$("intervalValue"),save:$("saveSettings")};
let loc=null,planes=[],view="nearest",timer=null,rotateTimer=null,lastAlert="";
let settings={radius:+localStorage.getItem("npRadius")||75,interval:+localStorage.getItem("npInterval")||30,alert:+localStorage.getItem("npAlert")||2,sound:localStorage.getItem("npSound")==="1",theme:localStorage.getItem("npTheme")||"airport"}; document.documentElement.dataset.theme=settings.theme;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function dist(a,b,c,d){const r=x=>x*Math.PI/180,R=3440.065,dl=r(c-a),dn=r(d-b),q=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function compass(d){return Number.isFinite(d)?["N","NE","E","SE","S","SW","W","NW"][Math.round(d/45)%8]:"—"}
function carrier(call){return carriers[(call||"").trim().slice(0,3).toUpperCase()]||"Private / General Aviation"}
function norm(a){const lat=+a.lat,lon=+a.lon;if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;const ab=+a.alt_baro,ag=+a.alt_geom,gs=+a.gs,tr=+a.track;return{call:(a.flight||a.callsign||"No callsign").trim(),reg:a.r||"Unknown",hex:(a.hex||"Unknown").toUpperCase(),type:a.t||a.type||"Unknown aircraft",desc:a.desc||"",operator:a.ownOp||a.operator||"",lat,lon,altitude:Number.isFinite(ab)?ab:Number.isFinite(ag)?ag:null,speed:Number.isFinite(gs)?gs:null,track:Number.isFinite(tr)?tr:null,distance:dist(loc.latitude,loc.longitude,lat,lon)}}
function nearest(){const p=planes[0];if(!p)return '<div class="message">No aircraft detected nearby. I’ll keep checking.</div>';return `<div class="airline">${esc(p.operator||carrier(p.call))}</div><div class="identity"><span>${esc(p.call)}</span><span class="type">${esc(p.type)}</span></div>${p.desc?`<div class="operator-line">${esc(p.desc)}</div>`:""}<div class="identifiers"><span>REG: ${esc(p.reg)}</span><span>ICAO: ${esc(p.hex)}</span><span>CARRIER ID: ${esc((p.call||"---").slice(0,3))}</span></div><div class="metrics"><div class="metric"><span class="label">Altitude</span>${p.altitude===null?"—":Math.round(p.altitude).toLocaleString("en-GB")+" FT"}</div><div class="metric"><span class="label">Speed</span>${p.speed===null?"—":Math.round(p.speed*1.15078)+" MPH"}</div><div class="metric"><span class="label">Distance</span>${(p.distance*1.15078).toFixed(1)} MI</div><div class="metric"><span class="label">Heading</span>${p.track===null?"—":Math.round(p.track)+"° "+compass(p.track)}</div></div>`}
function nearby(){return `<div class="nearby-title">NEARBY AIRCRAFT</div><div class="nearby-list">${planes.slice(0,9).map(p=>`<div class="nearby-row"><strong>${esc(p.call)}</strong><span>${esc(p.operator||carrier(p.call))}</span><span>${(p.distance*1.15078).toFixed(1)} mi</span><span>${p.altitude?Math.round(p.altitude).toLocaleString("en-GB")+" ft":"—"}</span></div>`).join("")||'<div class="message">No aircraft detected.</div>'}</div>`}
function radar(){return `<div class="radar-wrap"><span class="radar-home">⌂</span>${planes.slice(0,25).map((p,i)=>{const ang=(p.track||i*37)*Math.PI/180,r=Math.min(p.distance/settings.radius,1)*44,x=50+Math.sin(ang)*r,y=50-Math.cos(ang)*r;return `<span class="blip" style="left:${x}%;top:${y}%">✈<span class="blip-label">${esc(p.call)}</span></span>`}).join("")}<span class="radar-range">${settings.radius} NM</span></div>`}
async function weather(){ui.screen.innerHTML='<div class="message">Loading Manchester Airport weather…</div>';try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${MAN.lat}&longitude=${MAN.lon}&current=temperature_2m,apparent_temperature,wind_speed_10m,wind_direction_10m,visibility,cloud_cover&wind_speed_unit=mph&timezone=Europe%2FLondon`,{cache:"no-store"}),d=await r.json(),c=d.current;ui.screen.innerHTML=`<div class="weather-title">MANCHESTER AIRPORT · EGCC</div><div class="weather-grid"><div class="card"><small>Temperature</small><strong>${Math.round(c.temperature_2m)}°C</strong></div><div class="card"><small>Feels like</small><strong>${Math.round(c.apparent_temperature)}°C</strong></div><div class="card"><small>Wind</small><strong>${Math.round(c.wind_speed_10m)} MPH</strong></div><div class="card"><small>Wind direction</small><strong>${Math.round(c.wind_direction_10m)}° ${compass(c.wind_direction_10m)}</strong></div><div class="card"><small>Visibility</small><strong>${(c.visibility/1609.344).toFixed(1)} MI</strong></div><div class="card"><small>Cloud cover</small><strong>${Math.round(c.cloud_cover)}%</strong></div></div>`}catch(e){ui.screen.innerHTML='<div class="message error">Manchester weather could not be loaded.</div>'}}
function stats(){let s=JSON.parse(localStorage.getItem("npStats")||'{"seen":{},"closest":null,"highest":0,"fastest":0}');return `<div class="weather-title">TODAY'S AIRCRAFT</div><div class="stats-grid"><div class="card"><small>Unique aircraft seen</small><strong>${Object.keys(s.seen||{}).length}</strong></div><div class="card"><small>Closest</small><strong>${s.closest==null?"—":(s.closest*1.15078).toFixed(1)+" MI"}</strong></div><div class="card"><small>Highest</small><strong>${s.highest?Math.round(s.highest).toLocaleString("en-GB")+" FT":"—"}</strong></div><div class="card"><small>Fastest</small><strong>${s.fastest?Math.round(s.fastest*1.15078)+" MPH":"—"}</strong></div></div>`}
function render(){if(view==="nearest")ui.screen.innerHTML=nearest();else if(view==="nearby")ui.screen.innerHTML=nearby();else if(view==="radar")ui.screen.innerHTML=radar();else if(view==="weather")weather();else ui.screen.innerHTML=stats()}
function updateStats(){let today=new Date().toISOString().slice(0,10),s=JSON.parse(localStorage.getItem("npStats")||'null');if(!s||s.date!==today)s={date:today,seen:{},closest:null,highest:0,fastest:0};planes.forEach(p=>{s.seen[p.hex]=1;if(s.closest===null||p.distance<s.closest)s.closest=p.distance;if(p.altitude&&p.altitude>s.highest)s.highest=p.altitude;if(p.speed&&p.speed>s.fastest)s.fastest=p.speed});localStorage.setItem("npStats",JSON.stringify(s))}
function alertCheck(){const p=planes[0];if(!p||p.distance*1.15078>settings.alert||p.hex===lastAlert)return;lastAlert=p.hex;const b=document.createElement("div");b.className="alert-banner";b.innerHTML=`<div><strong>LOOK UP!</strong><small>${esc(p.call)} · ${(p.distance*1.15078).toFixed(1)} miles</small></div>`;b.onclick=()=>b.remove();document.body.appendChild(b);setTimeout(()=>b.remove(),6000);if(settings.sound){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=880;g.gain.value=.08;o.start();o.stop(a.currentTime+.25)}catch(e){}}}
async function load(){if(!loc)return locate();ui.live.textContent="Updating…";try{const r=await fetch(`${API}/point/${loc.latitude}/${loc.longitude}/${settings.radius}`,{cache:"no-store"}),d=await r.json(),list=Array.isArray(d.ac)?d.ac:(Array.isArray(d.aircraft)?d.aircraft:[]);planes=list.map(norm).filter(Boolean).sort((a,b)=>a.distance-b.distance);updateStats();render();alertCheck();ui.updated.textContent=`Updated ${new Date().toLocaleTimeString("en-GB")}`;ui.live.textContent="Live"}catch(e){ui.screen.innerHTML='<div class="message error">The live aircraft service could not be reached. Tap Refresh to try again.</div>';ui.live.textContent="Offline"}}
function locate(){navigator.geolocation.getCurrentPosition(p=>{loc=p.coords;load();clearInterval(timer);timer=setInterval(load,settings.interval*1000)},()=>{ui.screen.innerHTML='<div class="message error">Please allow location access for this website.</div>';ui.live.textContent="Location blocked"},{enableHighAccuracy:true,timeout:15000,maximumAge:300000})}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");view=b.dataset.view;render()}));
const rotateBtn=document.getElementById("rotateButton");if(rotateBtn)rotateBtn.onclick=()=>{if(rotateTimer){clearInterval(rotateTimer);rotateTimer=null;rotateBtn.textContent="Auto: Off"}else{const vs=["nearest","radar","nearby","weather","stats"];let i=vs.indexOf(view);rotateTimer=setInterval(()=>{i=(i+1)%vs.length;view=vs[i];document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===view));render()},15000);rotateBtn.textContent="Auto: On"}};
ui.refresh.addEventListener("click",load);ui.settingsBtn.addEventListener("click",()=>ui.dialog.showModal());ui.save.addEventListener("click",()=>{});setInterval(()=>{const c=document.getElementById("clock");if(c)c.textContent=new Date().toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})},1000);if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});locate();
})();